---
title: "Group 7: Covid-19 Forecast and Analysis"
author: "George Garcia, Torreon Green, Alexander Nguyen, Edgar Sosa Leal"
date: "4/18/2020"
output: powerpoint_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
library(skimr)
library(tidyverse)
library(forecast)
library(BatchGetSymbols)
options(scipen = 999, digits = 3)
```

## The Data

```{r}
load(file = "coronavirus.rda")
covidData <- read.csv("C:/Users/george/Documents/R Assignments/INFS 6359 Data Mining for Business Analytics/Group-7-Covid-19-ML-Project/covid-statistics-by-us-states-daily-updates.csv", header = TRUE)
head(covidData)
```

## Compute the number of positive cases daily

```{r, echo=TRUE}
covid.diff <-covidData %>%
    group_by(state) %>%
    mutate(Diff = positive - lead(positive))

covidData.sort2 <- covid.diff %>%
   arrange(date)

covid.sort3 <- covidData.sort2 %>%
  group_by(date) %>%
  summarize(totals = sum(Diff)) 

covid.sort3
```

## U.S. Confirmed Cases

```{r, echo=TRUE}

corona <- coronavirus %>%
  filter(Country.Region == "US") %>%
  filter(type == "confirmed")

coronaCases <- corona[, c(5, 6)]

coronaTotal <- coronaCases %>%
  mutate(total = cumsum(cases))

coronaTotal[82:88, ] # Validation set

```

## Time Series Exponential Model

```{r, echo=TRUE}
coronaTrain <- coronaTotal[1:81, ]
coronaValid <- coronaTotal[82:88, ]

coronaTrainTS <- ts(coronaTrain$total,
            start = 1,
            end = 81,
            freq = 1)

coronaValidTS <- ts(coronaValid$total,
                   start = 82,
                   end = 88,
                   freq = 1)

modelLM <- tslm(coronaTrainTS ~ trend, lambda = 0) # Lambda = 0 for exponential fit.

summary(modelLM)
```

## Random Walk Test

- AR(1) model slope coefficient is within 5 standard errors of 1
- Fails random walk test -> stick to naive LM

```{r, echo=TRUE}
modelARIMA <- Arima(modelLM$residuals, order = c(1,0,0))
predictARIMA <- forecast(modelARIMA, h = 7)

summary(modelARIMA)
```

## Forecast: Post- April 12, 2020

```{r}
coronaPredict <- forecast(modelLM, h = 7, level = 0)

plot(coronaTrainTS, 
     xlab = "# of Days", 
     ylab = "U.S. Total Confirmed Cases",
     ylim = c(1, 800000),
     xlim = c(1, 100),
     col = "blue",
     lty = 1)
lines(coronaPredict$fitted, 
      lty = 2,
      col = "red")
lines(coronaValidTS, 
      lty = 1, 
      col = "blue")
lines(c(82:88), coronaPredict$mean, 
      col = "red",
      lty = 2)
legend(1, 800000, 
       legend = c("Actual", "Predicted"), 
       col = c("blue", "red"), 
       lty = 1:2)

```

## Quadratic Model

```{r}
modelQuad <- tslm(coronaTrainTS ~ trend + I(trend^2)) # Quad fit

summary(modelQuad)
```

```{r, include=FALSE}
quadARIMA <- Arima(modelQuad$residuals, order = c(1,0,0), method = "ML")
predictQuad <- forecast(quadARIMA, h = 7)

summary(predictQuad)
```

## Quadratic Model

```{r, echo=FALSE}
plot(coronaTrainTS, 
     xlab = "# of Days", 
     ylab = "U.S. Total Confirmed Cases",
     ylim = c(1, 1000000),
     xlim = c(1, 100),
     col = "blue",
     lty = 1)
lines(predictQuad$fitted, 
      lty = 2,
      col = "red")
lines(coronaValidTS, 
      lty = 1, 
      col = "blue")
lines(predictQuad$mean, 
      lty = 2,
      col = "red")
legend(1, 800000, 
       legend = c("Actual", "Predicted"), 
       col = c("blue", "red"), 
       lty = 1:2)
```

## Part II: Impact on S&P 500

```{r, echo=TRUE}
companies <- 'SPY'
begin <- Sys.Date() - 200
end <- Sys.Date()

stockData <- BatchGetSymbols(tickers = companies,
                             first.date = begin,
                             last.date = end,
                             do.cache = FALSE)

SPY <- stockData$df.tickers %>%
  filter(ticker == "SPY")
head(SPY)

SPYTrain <- SPY[1:97, ]
SPYValid <- SPY[98:136, ]
```

## Quadratic Model

```{r}
# Time series til Feb 19, 2020
SPYTS <- ts(SPYTrain$price.close,
            start = c(2019, 10),
            end = c(2020, 02),
            freq = 97)

SPYValidTS <- ts(SPYValid$price.close,
                   start = c(2020, 02),
                   end = c(2020, 04),
                   freq = 41)

SPYQuad <- tslm(SPYTS ~ trend + I(trend^2))
summary(SPYQuad)
```

## Forecast

```{r}
# Forecast after Feb 20, 2020
SPYPredict <- forecast(SPYQuad, level = 95)

plot(SPYPredict, xlab = "Time",
     ylab = "SPY Close Price",
     #ylim = c(200, 400),
     bty = "l",
     xaxt = "n",
     flty = 2)
lines(SPYPredict$fitted, lwd = 2, col = "blue")
lines(SPYValidTS, lwd = 2, col = "red", lty = 3)
```

